#!/usr/bin/env bash
# Title: BL-060 Phase B Listening Test Harness QA Lane
# Document Type: QA Script
# Author: APC Codex
# Created Date: 2026-03-17
# Last Modified Date: 2026-03-17
#
# Exit codes:
#   0 all checks passed
#   1 one or more checks failed
#   2 usage/configuration error
#
# Phase B protocol: 2×2 blind listening test
#   Factor A: HRTF  — generic vs personalized
#   Factor B: EQ    — no EQ vs WH-1000XM5 EQ
#   Participants: >=5
#   Scenes:       >=10 per condition
#   Gate: >=20% mean externalization improvement OR p<0.05 localization gain
#
# Required pre-requisites (not enforced here; operator must verify):
#   - BL-059 Done-candidate (calibration handoff done)
#   - CalibrationProfile.json with personalized HRTF set
#   - Trial log CSV path provided (--trial-log) or generated by companion
#   - Analysis script path provided (--analysis-script) or auto-located

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="${ROOT_DIR}/TestEvidence/bl060_phase_b_listening_${TIMESTAMP}"
MODE="contract_only"
TRIAL_LOG_PATH=""
ANALYSIS_SCRIPT=""

STATUS_TSV=""
METRICS_TSV=""

pass_count=0
fail_count=0
todo_count=0

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
usage() {
  cat <<'USAGE'
Usage: qa-bl060-phase-b-listening-harness-mac.sh [options]

BL-060 Phase B listening test harness QA lane.

Options:
  --out-dir <path>         Artifact output directory (default: auto-timestamped)
  --trial-log <path>       Path to trial_log.csv generated by companion/operator
  --analysis-script <path> Path to analysis script (default: scripts/bl060-analyze.py)
  --contract-only          Contract / structure checks only (default)
  --execute                Execute-mode gate checks (fails while TODO rows remain)
  --help, -h               Show usage

Required trial_log.csv columns:
  condition, true_angle_deg, response_angle_deg, absolute_error_deg,
  reaction_time_ms, participant_id, scene_id

Outputs:
  status.tsv
  metrics_summary.tsv
  stats_report.md          (populated by --execute when analysis script runs)
  gate_decision.md         (populated by --execute)
  reproducibility_check.tsv (populated by --execute with >=2 runs)

Platform: macOS only.
USAGE
}

usage_error() {
  local message="$1"
  echo "ERROR: ${message}" >&2
  usage >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)      OUT_DIR="$2";            shift 2 ;;
    --trial-log)    TRIAL_LOG_PATH="$2";     shift 2 ;;
    --analysis-script) ANALYSIS_SCRIPT="$2"; shift 2 ;;
    --contract-only) MODE="contract_only";   shift ;;
    --execute)       MODE="execute";         shift ;;
    --help|-h)       usage; exit 0 ;;
    *) usage_error "Unknown argument: $1" ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "ERROR: This script is macOS-only." >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
record() {
  local check_id="$1"
  local result="$2"
  local detail="$3"
  local artifact="${4:-}"

  printf "%s\t%s\t%s\t%s\n" \
    "$check_id" \
    "$result" \
    "${detail//$'\t'/ }" \
    "${artifact//$'\t'/ }" \
    >> "$STATUS_TSV"

  if [[ "$result" == "PASS" ]]; then
    ((pass_count++)) || true
  elif [[ "$result" == "TODO" ]]; then
    ((todo_count++)) || true
  else
    ((fail_count++)) || true
  fi
}

record_todo() {
  record "$1" "TODO" "$2" "${3:-}"
}

# ---------------------------------------------------------------------------
# Setup output directory
# ---------------------------------------------------------------------------
mkdir -p "$OUT_DIR"
STATUS_TSV="${OUT_DIR}/status.tsv"
METRICS_TSV="${OUT_DIR}/metrics_summary.tsv"

printf "check_id\tresult\tdetail\tartifact\n" > "$STATUS_TSV"
printf "condition\tparticipant_count\tscene_count\tmae_deg\tfront_back_rate\texternalization_score\n" > "$METRICS_TSV"

echo "== BL-060 Phase B Listening Test Harness =="
echo "mode:    $MODE"
echo "out_dir: $OUT_DIR"
echo ""

# ---------------------------------------------------------------------------
# C1: Runbook present
# ---------------------------------------------------------------------------
RUNBOOK="${ROOT_DIR}/Documentation/backlog/bl-060-phase-b-listening-test-harness.md"
if [[ -f "$RUNBOOK" ]]; then
  record "BL060-C1-runbook_exists" "PASS" "runbook present" "$RUNBOOK"
else
  record "BL060-C1-runbook_exists" "FAIL" "runbook missing" "$RUNBOOK"
fi

# ---------------------------------------------------------------------------
# C2: BL-059 Done-candidate gate
# ---------------------------------------------------------------------------
BL059_STATUS=$(python3 -c "
import json, sys
d = json.load(open('${ROOT_DIR}/status.json'))
notes = d.get('notes', '')
print('done-candidate' if 'BL-059' in notes and ('Done-candidate' in notes or 'done-candidate' in notes) else 'not-ready')
" 2>/dev/null || echo "unknown")

if [[ "$BL059_STATUS" == "done-candidate" ]]; then
  record "BL060-C2-bl059_gate" "PASS" "BL-059 is Done-candidate; BL-060 unblocked" "${ROOT_DIR}/status.json"
else
  record "BL060-C2-bl059_gate" "FAIL" "BL-059 not confirmed Done-candidate in status.json notes" "${ROOT_DIR}/status.json"
fi

# ---------------------------------------------------------------------------
# C3: Analysis script locatable
# ---------------------------------------------------------------------------
if [[ -z "$ANALYSIS_SCRIPT" ]]; then
  ANALYSIS_SCRIPT="${ROOT_DIR}/scripts/bl060-analyze.py"
fi

if [[ -f "$ANALYSIS_SCRIPT" ]]; then
  record "BL060-C3-analysis_script_exists" "PASS" "analysis script found" "$ANALYSIS_SCRIPT"
else
  record "BL060-C3-analysis_script_exists" "TODO" \
    "analysis script not yet authored: ${ANALYSIS_SCRIPT}" \
    "$ANALYSIS_SCRIPT"
fi

# ---------------------------------------------------------------------------
# C4: Trial log schema (contract-only: check path; execute: validate columns)
# ---------------------------------------------------------------------------
REQUIRED_COLUMNS="condition,true_angle_deg,response_angle_deg,absolute_error_deg,reaction_time_ms,participant_id,scene_id"

if [[ -z "$TRIAL_LOG_PATH" ]]; then
  record "BL060-C4-trial_log_schema" "TODO" \
    "no --trial-log provided; trial log not yet captured (requires live Phase B session)" \
    ""
else
  if [[ -f "$TRIAL_LOG_PATH" ]]; then
    HEADER=$(head -1 "$TRIAL_LOG_PATH" 2>/dev/null || echo "")
    MISSING_COLS=""
    IFS=',' read -ra REQ_COLS <<< "$REQUIRED_COLUMNS"
    for col in "${REQ_COLS[@]}"; do
      if ! echo "$HEADER" | grep -qF "$col"; then
        MISSING_COLS="${MISSING_COLS} ${col}"
      fi
    done
    if [[ -z "$MISSING_COLS" ]]; then
      record "BL060-C4-trial_log_schema" "PASS" "all required columns present" "$TRIAL_LOG_PATH"
    else
      record "BL060-C4-trial_log_schema" "FAIL" \
        "missing columns:${MISSING_COLS}" "$TRIAL_LOG_PATH"
    fi
  else
    record "BL060-C4-trial_log_schema" "FAIL" "trial log file not found: $TRIAL_LOG_PATH" "$TRIAL_LOG_PATH"
  fi
fi

# ---------------------------------------------------------------------------
# C5: Participant count gate (requires trial log)
# ---------------------------------------------------------------------------
if [[ -n "$TRIAL_LOG_PATH" && -f "$TRIAL_LOG_PATH" ]]; then
  PARTICIPANT_COUNT=$(awk -F',' 'NR>1 {print $6}' "$TRIAL_LOG_PATH" 2>/dev/null \
    | sort -u | grep -c . || echo "0")
  if [[ "$PARTICIPANT_COUNT" -ge 5 ]]; then
    record "BL060-C5-participant_count" "PASS" \
      "participant_count=${PARTICIPANT_COUNT} (>=5 required)" "$TRIAL_LOG_PATH"
  else
    record "BL060-C5-participant_count" "FAIL" \
      "participant_count=${PARTICIPANT_COUNT} (<5; minimum not met)" "$TRIAL_LOG_PATH"
  fi
else
  record "BL060-C5-participant_count" "TODO" \
    "no trial log available; participant count cannot be verified" ""
fi

# ---------------------------------------------------------------------------
# C6: Scene count gate per condition (requires trial log)
# ---------------------------------------------------------------------------
if [[ -n "$TRIAL_LOG_PATH" && -f "$TRIAL_LOG_PATH" ]]; then
  MIN_SCENES=$(awk -F',' 'NR>1 {print $1 "_" $7}' "$TRIAL_LOG_PATH" 2>/dev/null \
    | sort -u | awk -F'_' '{print $1}' | sort | uniq -c \
    | awk '{print $1}' | sort -n | head -1 || echo "0")
  if [[ "${MIN_SCENES:-0}" -ge 10 ]]; then
    record "BL060-C6-scene_count_per_condition" "PASS" \
      "min_scenes_per_condition=${MIN_SCENES} (>=10 required)" "$TRIAL_LOG_PATH"
  else
    record "BL060-C6-scene_count_per_condition" "FAIL" \
      "min_scenes_per_condition=${MIN_SCENES:-0} (<10 in at least one condition)" "$TRIAL_LOG_PATH"
  fi
else
  record "BL060-C6-scene_count_per_condition" "TODO" \
    "no trial log available; scene count cannot be verified" ""
fi

# ---------------------------------------------------------------------------
# E1: Execute-mode gate — analysis script runs successfully (execute only)
# ---------------------------------------------------------------------------
if [[ "$MODE" == "execute" ]]; then
  if [[ -f "$ANALYSIS_SCRIPT" && -n "$TRIAL_LOG_PATH" && -f "$TRIAL_LOG_PATH" ]]; then
    ANALYSIS_OUT="${OUT_DIR}/analysis_stdout.log"
    if python3 "$ANALYSIS_SCRIPT" \
        --trial-log "$TRIAL_LOG_PATH" \
        --out-dir "$OUT_DIR" \
        > "$ANALYSIS_OUT" 2>&1; then
      record "BL060-E1-analysis_script_runs" "PASS" \
        "analysis script exited 0" "$ANALYSIS_OUT"
    else
      record "BL060-E1-analysis_script_runs" "FAIL" \
        "analysis script exited non-zero; see $ANALYSIS_OUT" "$ANALYSIS_OUT"
    fi
  else
    record "BL060-E1-analysis_script_runs" "TODO" \
      "analysis script or trial log not available; execute gate pending" ""
  fi
fi

# ---------------------------------------------------------------------------
# E2: Execute-mode gate — phase B gate decision recorded (execute only)
# ---------------------------------------------------------------------------
if [[ "$MODE" == "execute" ]]; then
  GATE_DECISION="${OUT_DIR}/gate_decision.md"
  if [[ -f "$GATE_DECISION" ]]; then
    record "BL060-E2-gate_decision_exists" "PASS" \
      "gate_decision.md written by analysis script" "$GATE_DECISION"
  else
    record "BL060-E2-gate_decision_exists" "TODO" \
      "gate_decision.md not yet written (requires analysis script run)" "$GATE_DECISION"
  fi
fi

# ---------------------------------------------------------------------------
# E3: Execute-mode gate — zero TODO rows (execute only)
# ---------------------------------------------------------------------------
if [[ "$MODE" == "execute" ]]; then
  if [[ "$todo_count" -gt 0 ]]; then
    record "BL060-E3-execute_todo_rows" "FAIL" \
      "execute mode has ${todo_count} TODO row(s); all TODO gates must be resolved" \
      "$STATUS_TSV"
  else
    record "BL060-E3-execute_todo_rows" "PASS" \
      "execute mode has zero TODO rows" "$STATUS_TSV"
  fi
fi

# ---------------------------------------------------------------------------
# Lane result
# ---------------------------------------------------------------------------
LANE_RESULT="PASS"
if [[ "$fail_count" -gt 0 ]]; then
  LANE_RESULT="FAIL"
fi

printf "%s\t%s\t%s\t%s\n" \
  "lane_result" \
  "$LANE_RESULT" \
  "mode=${MODE};bl060_lane_$(echo "$LANE_RESULT" | tr '[:upper:]' '[:lower:]');pass=${pass_count};fail=${fail_count};todo=${todo_count}" \
  "$STATUS_TSV" \
  >> "$STATUS_TSV"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "== BL-060 Lane Result =="
echo "mode:   $MODE"
echo "pass:   $pass_count"
echo "fail:   $fail_count"
echo "todo:   $todo_count"
echo "result: $LANE_RESULT"
echo "artifacts: $OUT_DIR"

if [[ "$LANE_RESULT" == "FAIL" ]]; then
  exit 1
fi
exit 0
